[package]
name = "trading_engine"
version = "0.1.0"
edition = "2021"
author = "github.com/th3g3ntl3m3n"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.26"
rust_decimal_macros = "1.26"